config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/info'

  resources :goals

  root :to => redirect('/goals')
end

app/models/goal.rb
class Goal < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:description, :time_frame, :complete)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :time_frame %><br>
    <%= f.number_field :time_frame %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<div class="row">

  <div class="col-md-6"> 
    <h1>Goals</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Description</th>
          <th>Time frame</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @goals.each do |goal| %>
          <tr>
            <% if goal.complete != true %> 
            <td><%= goal.description %></td>
            <td><%= goal.time_frame %></td>
            <td><%= link_to 'Complete', id: goal.id, class: "complete" %></td> 
            <td><%= link_to 'Show', goal %></td>
            <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
            <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %> 
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Goal', new_goal_path %>
  </div> 

  <div class="col-md-6">
    <h1>Completed</h1> 

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Description</th>
          <th>Time frame</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @goals.each do |goal| %>
          <tr>
            <% if goal.complete == true %> 
            <td><%= goal.description %></td>
            <td><%= goal.time_frame %></td>
          </tr>
          <% end %> 
        <% end %>
      </tbody>
    </table>
  </div> 

</div> 

app/views/goals/new.html.erb
<h1>New goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Time frame:</strong>
  <%= @goal.time_frame %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @goal.complete %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eRace</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">eRace</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Goals</a></li>
      </ul>
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  <%= yield %>
</div>

<footer>
  <div class="container">
    Huhnique Development
  </div>
</footer>

<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>